services:
    Hazu.Serializer:
        class:     CCS\HazuBundle\Service\SerializerService
        arguments: ["@service_container"]
    Hazu:
        class:     CCS\HazuBundle\Service\HazuService
        arguments: ["@service_container"]